crossbar:
  build: ./crossbar
  ports:
   - "5080:8080"
  expose:
   - "8080"
  volumes:
   - ./crossbar:/app
  environment:
    - PYTHONUNBUFFERED=1
  command: crossbar start --cbdir /app/.crossbar
directory:
  build: .
  volumes:
   - .:/app
  links:
   - crossbar
  environment:
    - PYTHONUNBUFFERED=1
  command: ./scripts/startDirectory.sh 
