name: Tests

on:
- push
- pull_request

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Lint with pycodestyle
      run: |
        pip install pycodestyle
        pycodestyle src/
    - name: Run pytest
      run: |
        python setup.py pytest --addopts "--junitxml=test-results.xml"
